# NumPy基本操作

1. 创建数组

In [1]:
# 导入 numpy 模块
import numpy as np

# 将列表转换为 Numpy 数组
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [2]:
# 产看数组对象类型
a.dtype

dtype('int64')

In [3]:
# 将浮点数列转为 Numpy 数组
b = np.array([1.2, 2.3, 3.4])
b.dtype

dtype('float64')

In [4]:
# 也可转换多维数组
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 生成 2x3 的全 0 数组
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# 生成 3x4 的全 1 数组，并指定数据类型为 np.int16
np.ones((3, 4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [10]:
# 生成 大于等于10 小于30 步长为5 的数组
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [11]:
# 生成 3x2 符合 (0, 1)均匀分布的随机数组
np.random.rand(3, 2)

array([[0.68535724, 0.72673589],
       [0.48221039, 0.53679577],
       [0.65125542, 0.94370622]])

In [13]:
# 生成 0~2 范围内 整形 且长度为 5 的数组
np.random.randint(3, size=5)

array([2, 1, 0, 1, 0])

In [14]:
# 生成一个符合标准正太分布的数组
np.random.randn(3)

array([ 2.17625195, -1.54654062,  1.13322304])

2. 数组的索引与切片